### ISSUE TITLE
[Pokémon Platinum] Volkner Wrong Order

### ISSUE THREAD

**Issue by chrisasma103** [domtronn/dc-nuzlocke#104]
Volkner leads with a Jolteon, but not a Raichu. In the tracker, it says he leads with a Raichu
![Screenshot_20230403-205601](https://user-images.githubusercontent.com/41581802/229659004-aa22c6b2-0623-48e1-a947-c10e362c2d79.png)

**Comment by domtronn** [comment]
Thanks for raising! I've fixed this now
