### ISSUE TITLE
Crashing when adding 'Opponent Trainer' to a graveyard entry

### ISSUE THREAD

**Issue by voiceandtone** [domtronn/dc-nuzlocke#105]
When entering the encounter details on a defeated Pokemon, selecting an **Opponent Trainer** crashes the app and requires a page refresh. Have tested in Safari and Chrome across a few different games.

<img width="1150" alt="Screenshot 2023-04-05 at 10 21 16 AM" src="https://user-images.githubusercontent.com/66455768/229936302-17a1b410-800f-408b-a05f-24630a80fdbd.png">

- Google Chrome Console produced this error when running, if that's useful

```
PokemonIcon.svelte:7 
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at Object.h (PokemonIcon.svelte:7:27)
    at Object.c (PokemonIcon-d914e690.js:1:306)
    at Ye (index.mjs:1923:20)
    at Object.c (FormBoss.svelte:123:22)
    at Object.c (AutoComplete.svelte:72:22)
    at Object.c (AutoComplete.svelte:69:24)
    at Object.c (SimpleAutocomplete.svelte:1239:56)
    at Object.c (SimpleAutocomplete.svelte:1201:80)
    at Object.c (SimpleAutocomplete.svelte:1200:13)
    at Object.c (SimpleAutocomplete.svelte:1249:28)
h @ PokemonIcon.svelte:7
c @ PokemonIcon-d914e690.js:1
Ye @ index.mjs:1923
c @ FormBoss.svelte:123
c @ AutoComplete.svelte:72
c @ AutoComplete.svelte:69
c @ SimpleAutocomplete.svelte:1239
c @ SimpleAutocomplete.svelte:1201
c @ SimpleAutocomplete.svelte:1200
c @ SimpleAutocomplete.svelte:1249
Ye @ index.mjs:1923
c @ AutoComplete.svelte:42
Ye @ index.mjs:1923
c @ FormBoss.svelte:110
p @ FormBoss.svelte:107
Jt @ index.mjs:1193
it @ index.mjs:1160
Promise.then (async)
kt @ index.mjs:1118
Yt @ index.mjs:1965
(anonymous) @ index.mjs:2003
g @ FormBoss.svelte:81
u @ FormBoss.svelte:146
(anonymous) @ index.mjs:2001
M @ AutoComplete.svelte:49
F @ AutoComplete.svelte:65
(anonymous) @ index.mjs:2001
rl @ SimpleAutocomplete.svelte:607
al @ SimpleAutocomplete.svelte:717
mn @ SimpleAutocomplete.svelte:1206
r @ SimpleAutocomplete.svelte:1239

```

**Comment by voiceandtone** [comment]
BTW great little app you've got here @domtronn! The consideration and care you've put into it's presentation makes it a lot more enjoyable to use than the other options out there.

**Comment by domtronn** [comment]
Thanks for raising this bug @voiceandtone!
Annoying that it got in and I'm sorry for the inconvenience... But I've pushed up a fix now and it should be working again!

Also, thank you for the feedback 🙁 That's absolutely what I'm going for, when I wanted to track my nuzlockes I found a lot of the tools overwhelming so the core philosophy is to keep the interactions and UX as simple as possible!

If you have any other feedback or ideas please do reach out on GitHub or [Discord](https://discord.gg/rKXkJjuZ)
