### ISSUE TITLE
App not functioning properly on Firefox?

### ISSUE THREAD

**Issue by stellanation** [domtronn/dc-nuzlocke#143]
**Describe the bug**
When trying to use the app on Firefox, can't click on any of the 'Gen (number)' tabs after 'New Game' or any of the game icons to start a new nuzlocke.

**To Reproduce**
1. Access the page with the Firefox browser
2. Click on 'New Game'
3. Click on any of the generation tabs or game icons

**Expected behavior**
Probably goes without saying, but I was expecting it to highlight the game and let me use the app.

**Screenshots**
When I used F12 I saw this. I don't really have any actual experience with coding and have no idea what it means, but maybe it means something?
![image](https://github.com/domtronn/nuzlocke.app/assets/143217949/08450753-c3a1-4a99-bacd-e81f50f78f42)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 116

**Additional context**
I'm assuming that it has to do with using Firefox as opening the app on my phone or in a different browser on the same computer has it work fine.

**Comment by gr3ger** [comment]
Works fine for me on Firefox 116.0.3 (64-bit) (win11)

**Comment by stellanation** [comment]
looks like it's just an issue on my end, then, but ty
