### ISSUE TITLE
Byron's Steelix/Bastiodon use their Diamond/Pearl levels and hold items rather than their Platinum ones during Platinum runs.

### ISSUE THREAD

**Issue by BallisticLG** [domtronn/dc-nuzlocke#33]
**Describe the bug**
Title. Rather than using the Platinum levels and items for Steelix and Bastiodon on Byron's team, the Diamond and Pearl levels and items are used instead. Notably the movesets are correct. This notably means that the level cap for Byron is listed as 39 rather than 41 like it is in Platinum.

**To Reproduce**
1. Create a New Nuzlocke with Pokemon Platinum as the game selected.
2. Go to the bosses tab and scroll down to Byron.
3. You'll see that Byron's Bastiodon and Steelix have their Diamond/Pearl levels and items rather than their Platinum ones.

**Expected behavior**
Byron's Steelix should be level 38 instead of level 36 and Byron's Bastiodon should be level 41 with a Sitrus Berry rather than level 39 with a Chesto Berry.

**Screenshots**
![image](https://user-images.githubusercontent.com/85038238/147423785-fd0ce379-4b77-4e9b-b7d8-ae1c55b2e0b1.png)
![image](https://user-images.githubusercontent.com/85038238/147423793-f1868929-4e8f-4292-9ea7-70317f71f274.png)

**Desktop (please complete the following information):**
 - OS: Shouldn't matter
 - Browser: Opera
 - Version: Opera 82

**Additional context**
Made my current run slightly more tricky since I was actually a couple levels under the level cap, even some of the gym trainers were harder than they should have been :x

**Comment by domtronn** [comment]
Thanks for raising and thanks for all of the detail! 
I've pushed up a fix now so the updated data should be available shortly 👍

**Comment by domtronn** [comment]
<img width="1167" alt="Screenshot 2022-01-03 at 22 33 52" src="https://user-images.githubusercontent.com/5881414/147987680-ccbbf625-9161-459e-ad7d-135aee031c85.png">
Looks good now - might need a hard refresh to bust any caches :)
