### ISSUE TITLE
Route 46 listed much later than potentially available

### ISSUE THREAD

**Issue by DarkShinyLugia** [domtronn/dc-nuzlocke#34]
**Describe the bug**
Route 46 is listed below Clair, as though the generator expects you to go to the northern section of the route. However, the route is available as early as you can obtain Pokeballs by going north from 29.

**To Reproduce**
Go to Clair's boss fight, and below it is Route 45 (properly inaccessible until later) and 46 (accessible as soon as you have a starter) Tested on Silver Version, also occurs on Crystal and HeartGold.

**Expected behavior**
Route 46 should be earlier on the generator, as it is available far earlier on in the game. This is so that the generator does not ask you to "continue at route 27" when the player is far behind that point.

**Screenshots**
![image](https://user-images.githubusercontent.com/26509863/147839035-7ca1854f-a6e3-470b-9f24-a34628877679.png)

**Additional context**
https://bulbapedia.bulbagarden.net/wiki/Johto_Route_46

**Comment by domtronn** [comment]
Thanks for raising and thanks for all of the detail!
I've pushed up a change moving Route 46 to just after Route 29 - I never know the best way to handle routes that can be accessed early with multiple areas and equally I've not played every game in a long while so if you spot any other incorrect order please raise another issue
