### ISSUE TITLE
Pokemon Renegade Platinum Saturn's Valor Cavern Fight Shows Wrong Team

### ISSUE THREAD

**Issue by WaffleHat73** [domtronn/dc-nuzlocke#40]
**Describe the bug**
Not so much a bug, just an error.

**To Reproduce**
1. Go to Bosses'
2. Click on 'Evil team'
3. Scroll down to 'Saturn - Valor Cavern'
4. See error - Show's Saturn's team for battle at Galactic HQ.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by domtronn** [comment]
![Image](https://user-images.githubusercontent.com/5881414/222767722-2be1a6e7-f18e-4c71-933a-27fb4b7ef4ed.png)
![Image](https://user-images.githubusercontent.com/5881414/222767723-8fe74e9f-5bf9-4b6f-ad89-f29886237b96.png)
