### ISSUE TITLE
[Black] Bianca's teams for Driftveil City and Moor of Iccirus are switched

### ISSUE THREAD

**Issue by EthanM827** [domtronn/dc-nuzlocke#45]
**Describe the bug**
On the main page for a Pokemon Black nuzlocke, Bianca's team is shown as lvl 38-40 and fully evolved under the Driftveil City fight dropdown menu, and as lvl 26-28 and not fully evolved under the Moor of Iccirus fight section, rather than the other way around.

**Screenshots**
![driftveil](https://user-images.githubusercontent.com/33532968/177838240-9cf39159-88dc-4091-88bf-cb04e41a2e6f.png)
![moor](https://user-images.githubusercontent.com/33532968/177838218-6dfeb5d6-4ed2-4ae3-af9b-fc0322a36edf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 102.0

**Comment by domtronn** [comment]
Duplicated by #65
