### ISSUE TITLE
[Omega Ruby/Alpha Sapphire] Phoebe's team

### ISSUE THREAD

**Issue by Augie279** [domtronn/dc-nuzlocke#46]
**Describe the bug**
Omega Ruby's Phoebe has a Banette listed as being level 41 instead of 51.

**To Reproduce**
1. Go to Omega Ruby's nuzlocke
2. Click on Phoebe's team
3. Scroll down to the Banette

**Expected behavior**
It should be level 51 but isn't.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://media.discordapp.net/attachments/988174840924106762/997388764492079134/unknown.png)

**Desktop (please complete the following information):**
OS: Windows
Browser: Firefox

**Additional context**
Nothing else needed to be said.

**Comment by domtronn** [comment]
Thanks for raising! I've fixed the level 51 banette



![Image](https://user-images.githubusercontent.com/5881414/222772899-04e18dbd-15fc-419a-9548-3a4c18fed7a4.png)
