### ISSUE TITLE
Site not loading

### ISSUE THREAD

**Issue by amlive** [domtronn/dc-nuzlocke#49]
Hi, not sure if this is something you can fix, but the site nuzlocke.app won't load past the initial "continue game" page. The pokeball loading animation just continues forever. The rest of my internet is working fine, so I don't think it's bad connection for me. Just wanted to let you know in case there's something you the coder can do about it. Thanks!

**Comment by domtronn** [comment]
Thanks for raising! This was an issue with the site hosting, and should be resolved now

Let me know if the problem persists.
