### ISSUE TITLE
Routes 105, 111, and 120 show incorrect encounters (Only the Regi Trio) (Pokemon Emerald)

### ISSUE THREAD

**Issue by WertioEgg** [domtronn/dc-nuzlocke#54]
**Describe the bug**
Routes 105, 111, and 120 show the Regis as the only possible encouter suggestions there by deafault (you can still manually enter other pokemon). For example, 

**To Reproduce**
1. Go to 'Emerald Nuzlocke'
2. Click on 'Find Encounter' on routes 1-5, 111, or 120

**Expected behavior**
It should show the full encounter lists for these routes (eg. Sandshrew, Trappinch etc. on route 111)

**Screenshots**
![image](https://user-images.githubusercontent.com/113299584/189535533-0f86631c-f42b-40c8-91da-8352041bede4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Additional context**

**Comment by domtronn** [comment]
Ive regenerated the route information for emerald from PokemonDB and it's pulled through more encounters on these routes.

Thanks for raising!

You can always type in the name of any pokemon as well just in case they're missing
