### ISSUE TITLE
May's team

### ISSUE THREAD

**Issue by Tenebrarum777** [domtronn/dc-nuzlocke#56]
**Describe the bug**
May has a torkoal in Rustboro when selecting Torchic as a starter. It currently shows as a slugma.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by domtronn** [comment]
I did not know that, and took a while to find a source that showed me the torkoal and it's stats

![Image](https://user-images.githubusercontent.com/5881414/222770188-13c34083-35aa-4f34-8256-136a0c007145.png)

!
