### ISSUE TITLE
[Platinum] Barry's 6th Team is a Copy of his 5th Team

### ISSUE THREAD

**Issue by chrisasma103** [domtronn/dc-nuzlocke#57]
**Describe the bug**
When looking at Barry's final team on the website, the team make-up is identical to his 5th fight. In the game, Barry's final team is different from his 5th team

**To Reproduce**
1. Start a Pokemon Platinum Nuzlocke
2. Scroll down to Barry's final fight (right before the Elite 4)

**Expected behavior**
Barry's final team should have six Pokemon. This wikia page should have the correct information on his team: https://bulbapedia.bulbagarden.net/wiki/Barry_(game)/Platinum

**Screenshots**
https://i.gyazo.com/c9747bf41d0ea11a09ac710b7b511fe2.png

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox

**Comment by domtronn** [comment]
I had an extra barry fight at the end of Victory Road (I think left over from Diamond & Pearl's data) which was a copy of his fifth fight.

Now there's only the pokemon league fight, which is different 

![Image](https://user-images.githubusercontent.com/5881414/222768760-6ae9a443-9501-4df4-b15a-1a69c45d0ce2.png)
