### ISSUE TITLE
[Platinum] Mt. Coronet has the wrong encounters (Only Regice)

### ISSUE THREAD

**Issue by chrisasma103** [domtronn/dc-nuzlocke#58]
**Describe the bug**
Mt. Coronet's default encounter lists only Regice.

**To Reproduce**
1. Make a new Platinum Nuzlocke
2. Scroll down to the Mt. Coronet encounters and click "find encounters"

**Expected behavior**
The actual encounters found in Mt. Coronet should appear instead. Here is a link which contains them: https://m.bulbapedia.bulbagarden.net/wiki/Mount_Coronet

**Screenshots**
(https://i.gyazo.com/e2edbd01c826ef87d9d5ab32d0230c66.png)

**Comment by domtronn** [comment]
I've regenerated a lot of the Platinum route encounters based on Pokemon DB
They should be more correct now! 

![Image](https://user-images.githubusercontent.com/5881414/222768367-09f28cb1-cfcd-4b47-9bb8-1a26ad708b64.png)
