### ISSUE TITLE
Pokemon Ruby Elite 4 missing Drake

### ISSUE THREAD

**Issue by RobinClaesson** [domtronn/dc-nuzlocke#63]
**Describe the bug**
The elite 4 for pokemon ruby is missing Drake and his team. 

**Screenshots**
https://imgur.com/a/eQcht97

**Comment by RobinClaesson** [comment]
The same is true for Saphire

**Comment by domtronn** [comment]
Not sure how I missed adding him at all! 
But he's back in all his glory



![Image](https://user-images.githubusercontent.com/5881414/222770596-5888652c-d249-4418-9a72-8470e25602b4.png)
