### ISSUE TITLE
Missing An encounter for Inclement Emerald!

### ISSUE THREAD

**Issue by evan1017** [domtronn/dc-nuzlocke#64]
**Describe the bug**
Missing the route 109 encounters! 

**Expected behavior**
should be right before the slateport encounter!

**Screenshots**
<img width="1022" alt="Screen Shot 2023-01-14 at 1 27 34 AM" src="https://user-images.githubusercontent.com/51813665/212461271-5539d6c8-0bb9-47ee-9e5c-763d11fbbe7f.png">

-browser- Chrome

**Comment by domtronn** [comment]
Route 109 was in the game, but much further down! Thanks for raising, it's hard to know the right orders of routing for rom hacks when I've never played them.

I've moved it before slate port as in the screenshot, if you can't find a route in the future try the search as well 😃  

![Image](https://user-images.githubusercontent.com/5881414/222769496-85c772f2-827a-44c7-87ad-c4c79200b3da.png)
