### ISSUE TITLE
Nullable runtime error

### ISSUE THREAD

**Issue by dallenbaldwin** [domtronn/dc-nuzlocke#76]
**Describe the bug**
Cannot read properties of undefined when trying to click the Research team button in the box. Looks like you need to null coalesce  analysis or initialize it to an empty array 

Freezes UI

**To Reproduce**
Box: https://nuzlocke.app/drop/2jxveec8
Click Research team

**Expected behavior**
Be able to use the Research team feature

**Screenshots**
![image](https://user-images.githubusercontent.com/14098845/224616873-3184fbd0-c487-4f4d-842d-18ed74e26293.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: Version 1.49.120 Chromium: 111.0.5563.64 (Official Build) (64-bit)

**Comment by domtronn** [comment]
Thanks for raising and th drop link! 
Very useful for debugging.

I'm pretty sure this was fixed from [this thread](https://discord.com/channels/917869259261100142/1083648424760594432) in Discord, but let me know if you still see it.
