### ISSUE TITLE
[Pokémon Platinum] Some Routes are Out of Order

### ISSUE THREAD

**Issue by chrisasma103** [domtronn/dc-nuzlocke#82]
In the list of routes for the game, some of them are not in the position they are first accessible.

Example 1: you can access the west side of Route 211 as soon as you reach Eterna City. However, in the tracker, Route 211 is listed after Iron Island.
![Screenshot_20230323-123123](https://user-images.githubusercontent.com/41581802/227272953-e63efaf1-f817-4740-8cb6-76fd0845b1ba.png)

Example 2: you access route 213 on the way to route 212. You cannot access route 212 from Hearthome until you reach Pastoria city. Therefore the order should be Route 213 -> Pastoria City -> Route 212. However, in the tracker, Route 212 is listed before Route 213 and both are listed before Pastoria City.
![Screenshot_20230323-123733](https://user-images.githubusercontent.com/41581802/227273349-e9be04ee-f4cd-434d-ade8-8d1e39f096bd.png)

Example 3: you can access Mt. Coronet as soon as you enter Eterna city through Route 211. However, in the tracker, Mt. Coronet is listed after Eterna City and Wayback cave.
![Screenshot_20230323-123355](https://user-images.githubusercontent.com/41581802/227273869-170924ed-6d77-4a03-8441-16531893e9c2.png)

**Comment by domtronn** [comment]
Thanks @chrisasma103 !

Apologies that they were out of order, but I really appreciate the detail you put into these.
Since I can't play every nuzlocke in detail, I'm never sure of the best order for routes, e.g. as soon as they're accessible or when the whole thing opens up...

Anyway, I've reordered the examples above, and fixed #81 

Let me know if there are any other order oddities!

**Comment by chrisasma103** [comment]
No problem! To be honest, I thought something like this might not be worth it to even report. Your nuzlocke tracker is just really good, so I can't help but want to chime in with my thoughts. I'll let you know if I come across any other kinds of oddities in the tracker as I continue my Platinum nuzlocke.
