### ISSUE TITLE
[Pokémon Platinum] Rival Fight 5: Staravia Instead of Staraptor

### ISSUE THREAD

**Issue by chrisasma103** [domtronn/dc-nuzlocke#84]
When you fight Barry in Canalave City, his first Pokémon is a Staraptor. However, in the tracker, it is listed as a Staravia.
![Screenshot_20230325-142146](https://user-images.githubusercontent.com/41581802/227734829-2155c9c6-afdd-404d-bc53-3c69ad17abef.png)

**Comment by domtronn** [comment]
Thanks for raising! This should be fixed now
