### ISSUE TITLE
[Pokémon Platinum] Wrong Purugly

### ISSUE THREAD

**Issue by chrisasma103** [domtronn/dc-nuzlocke#85]
When you fight Mars at the lake near Twinleaf, she has a level 40 Purugly. However, the Purugly listed in the tracker is level 16.

![Screenshot_20230325-181219](https://user-images.githubusercontent.com/41581802/227744894-5fcf897d-f7e4-443e-9985-eb92a6cb9dc0.png)

**Comment by domtronn** [comment]
Thanks for raising! This and #84 should be fixed now ✌️
