### ISSUE TITLE
[Pokémon Platinum] No Distortion World Encounter

### ISSUE THREAD

**Issue by chrisasma103** [domtronn/dc-nuzlocke#96]
There is no encounter slot for catching Giratina. It goes from Snowpoint Temple to Route 222. There should be an encounter slot for Giratina in the Distortion World.
![Screenshot_20230329-200758](https://user-images.githubusercontent.com/41581802/228695594-5ca2393b-7a34-4522-a94f-1f5b55ee0187.png)

**Comment by domtronn** [comment]
Thanks again for raising these @chrisasma103 🙏 
I really appreciate you helping me fix the mistakes 😄
